version: "3"

services:
  realtime:
    image: "ghcr.io/gustavobertoi/realtime:latest"
    environment:
      APP_DEBUG: "1"
      GIN_MODE: "debug"
    ports:
      - 4567:4567
    networks:
      - realtime-network
    depends_on:
      - realtime-redis

  realtime-redis:
    image: "bitnami/redis:latest"
    environment:
      REDIS_PASSWORD: realtime
    ports:
      - 6379:6379
    volumes:
      - realtime-redis-volume:/bitnami/redis/data
    networks:
      - realtime-network

volumes:
  realtime-redis-volume:
    driver: local

networks:
  realtime-network:
    external: true
    driver: bridge
