version: "3"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      REDIS_PASSWORD: realtime
    ports:
      - 6379:6379
    volumes:
      - realtime-redis-volume:/bitnami/redis/data
    networks:
      - realtime-network

  redis-realtime-service:
    image: ghcr.io/open-source-cloud/realtime:latest
    depends_on:
      - redis-realtime-service
    environment:
      APP_DEBUG: "1"
      CONFIG_FOLDER_PATH: "configs/redis.config.yaml"
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/redis.config.yaml:/configs/redis.config.yaml
    networks:
      - realtime-network

volumes:
  realtime-redis-volume:
    driver: local

networks:
  realtime-network:
    external: true
    driver: bridge
